export global LKPalette {
    in property <brush> background: #1e1e2e;
    in property <brush> foreground: #cdd6f4;
    in property <brush> alternate-background: #181825;
    in property <brush> alternate-foreground: #bac2de;
    in property <brush> control-background: #313244;
    in property <brush> control-foreground: #cdd6f4;
    in property <brush> accent-background: #89b4fa;
    in property <brush> accent-foreground: #cdd6f4;
    in property <brush> selection-background: #b4befe;
    in property <brush> selection-foreground: #1e1e2e;
}