export global LKPalette {
    in property <color> background: #1e1e2e;
    in property <color> foreground: #cdd6f4;
    in property <color> alternate-background: #181825;
    in property <color> alternate-foreground: #bac2de;
    in property <color> control-background: #313244;
    in property <color> control-foreground: #cdd6f4;
    in property <color> accent-background: #89b4fa;
    in property <color> accent-foreground: #cdd6f4;
    in property <color> selection-background: #b4befe;
    in property <color> selection-foreground: #1e1e2e;
}