import { Style } from "@ui/globals.slint";

import { FontWeight } from "@ui/fonts/font_weight.slint";
import "@ui/fonts/JetBrainsMono-Regular.ttf";

export component SideBarItem inherits Rectangle {
    in property <string> label;
    in property <bool> is-active;

    callback activate;

    background: Style.palette.alternate-background;

    states [
        active when is-active: {
            background: Style.palette.background;
            indicator.height: self.height * 2 / 3;
            label.color: Style.palette.accent-background;

            in-out {
                animate background, indicator.height, label.color {
                    duration: 200ms;
                    easing: ease-in-out-back;
                }
            }
        }
    ]

    HorizontalLayout {
        padding: 8px;
        Rectangle {
            width: 8px;
            indicator := Rectangle {
                background: Style.palette.accent-background;
                border-radius: parent.width / 2;
            }
        }

        label := Text {
            vertical-alignment: center;
            horizontal-alignment: center;
            text: root.label;
            color: Style.palette.foreground;
            font-family: "JetBrains Mono";
            font-weight: FontWeight.BOLD;
            font-size: 25px;
        }
    }

    TouchArea {
        clicked => {
            root.activate();
        }
    }
}

export component SideBar inherits Rectangle {
    in-out property <int> active-page: 0;
    in property <length> item-height;

    callback activate(index: int);

    background: Style.palette.alternate-background;
    
    VerticalLayout {
        for label[index] in [
            "Instance", "Server", "Account", "Setting"
        ] : SideBarItem {
            label: label;
            height: root.item-height;
            is-active: root.active-page == index;
            activate => {
                root.active-page = index;
                root.activate(index);
            }
        }
    }
}