[package]
name = "kapplex_launcher_gui"
version = "0.1.0"
edition = "2024"

[[bin]]
path = "src/main.rs"
name = "kapplex_launcher"

[dependencies]
slint = "1.12.0"

[build-dependencies]
slint-build = "1.12.0"
