import { Palette } from "@style/palette.slint";

export global GlobalState {
    in property <Palette> palette: {
        background: #1e1e2e,
        foreground: #cdd6f4,
        alternate-background: #181825,
        alternate-foreground: #bac2de,
        control-background: #313244,
        control-foreground: #cdd6f4,
        accent-background: #89b4fa,
        accent-foreground: #cdd6f4,
        selection-background: #b4befe,
        selection-foreground: #1e1e2e,
    };
}