import { SideBar, SideBarItem } from "@components/sidebar.slint";
import { Style } from "@globals";

export * from "@globals";

export component MainWindow inherits Window {
    in-out property <int> active-page: 0;

    title: "LK Launcher";
    min-height: 500px;
    max-height: 10000px;

    background: Style.palette.background;

    HorizontalLayout {
        // Main View
        Rectangle {
            min-width: 600px;
            background: Style.palette.background;
        }

        SideBar {
            width: 200px;
            background: Style.palette.alternate-background;

            activate(index) => {
                root.active-page = index;
            }
        } 
    }
}