import { Style } from "@ui/globals.slint";
import { IndicatorPosition, FontWeight } from "@ui/enums.slint";

export component SideBarItem inherits Rectangle {
    in property <string> text <=> label.text;
    in property <length> font_size <=> label.font-size;
    in property <IndicatorPosition> indicator_position;
    in property <bool> is-active;

    callback activate;

    background: Style.palette.alternate-background;

    states [
        active when is-active: {
            background: Style.palette.background;
            indicator.height: self.height * 2 / 3;
            label.color: Style.palette.accent-background;

            in-out {
                animate background, indicator.height, label.color {
                    duration: 200ms;
                    easing: ease-in-out-back;
                }
            }
        }
    ]

    Rectangle {
        Rectangle {
            x: (indicator_position == IndicatorPosition.LEFT) ? 8px : parent.width - 2*8px;
            width: 8px;
            indicator := Rectangle {
                background: Style.palette.accent-background;
                border-radius: parent.width / 2;
            }
        }

        label := Text {
            vertical-alignment: center;
            horizontal-alignment: center;
            color: Style.palette.foreground;
            font-family: "JetBrains Mono";
            font-weight: FontWeight.BOLD;
            font-size: 25px;
        }
    }

    TouchArea {
        clicked => {
            root.activate();
        }
    }
}