import { SideBarItem } from "@ui/components/sidebar/sidebar_item.slint";

import { Style } from "@ui/globals.slint";
import { IndicatorPosition } from "@ui/enums.slint";

export component SideBar inherits Rectangle {
    in-out property <int> active-page: 0;
    in property <[string]> item-list;
    in property <length> item-height;
    in property <length> item-font-size;
    in property <int> item-font-weight;
    in property <IndicatorPosition> item-indicator-position;

    callback activate(index: int);

    background: Style.palette.alternate-background;
    
    VerticalLayout {
        for label[index] in root.item-list : SideBarItem {
            text: label;
            height: root.item-height;
            font_size: root.item-font-size;
            font-weight: root.item-font-weight;
            indicator_position: root.item-indicator-position;
            is-active: root.active-page == index;

            activate => {
                root.active-page = index;
                root.activate(index);
            }
        }
    }
}